// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)
