// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Representation of the information about a user sourced from Kratos.
type User struct {
	// The unique ID of the user.
	ID string `json:"id"`
	// The user's full name.
	Name *string `json:"name"`
	// The user's email address.
	Email string `json:"email"`
}
