// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// Input for adding a user to an organization as an administrator.
type Admin struct {
	// The ID of the user to add as an admin.
	ID string `json:"id"`
}

// Representation a group of users.
type Group struct {
	// The name of the group.
	Name string `json:"name"`
	// The users that are admins of the organization.
	Members []*User `json:"members"`
	// The organization that the group belongs to.
	Organization *Organization `json:"organization"`
}

// Representation of users and groups that are allowed to login with through OAuth2 Client.
type LoginBindings struct {
	// The users that are allowed to login with this OAuth2 Client.
	Users []*User `json:"users"`
	// The groups that are allowed to login with this OAuth2 Client.
	Groups []*Group `json:"groups"`
}

type LoginBindingsInput struct {
	// The users that are allowed to login with this OAuth2 Client.
	Users []string `json:"users"`
	// The groups that are allowed to login with this OAuth2 Client.
	Groups []string `json:"groups"`
}

// The first and last name of a user.
type Name struct {
	// The user's first name.
	First *string `json:"first"`
	// The user's last name.
	Last *string `json:"last"`
}

type NameInput struct {
	// The user's first name.
	First *string `json:"first"`
	// The user's last name.
	Last *string `json:"last"`
}

// Representation of the information about an OAuth2 Client sourced from Hydra.
type OAuth2Client struct {
	// OAuth 2.0 Client Allowed CORS Origins. AllowedCORSOrigins is an array of allowed CORS origins. If the array is empty, the value of the first element is considered valid.
	AllowedCorsOrigins []string `json:"allowedCorsOrigins"`
	// OAuth 2.0 Client Audience. Audience is an array of URLs that the OAuth 2.0 Client is allowed to request tokens for.
	Audience []string `json:"audience"`
	// Specify a time duration in milliseconds, seconds, minutes, hours. For example, 1h, 1m, 1s, 1ms.
	AuthorizationCodeGrantAccessTokenLifespan *string `json:"authorizationCodeGrantAccessTokenLifespan"`
	// Specify a time duration in milliseconds, seconds, minutes, hours. For example, 1h, 1m, 1s, 1ms.
	AuthorizationCodeGrantIDTokenLifespan *string `json:"authorizationCodeGrantIdTokenLifespan"`
	// Specify a time duration in milliseconds, seconds, minutes, hours. For example, 1h, 1m, 1s, 1ms.
	AuthorizationCodeGrantRefreshTokenLifespan *string `json:"authorizationCodeGrantRefreshTokenLifespan"`
	// OpenID Connect Back-Channel Logout Session Required  Boolean value specifying whether the RP requires that a sid (session ID) Claim be included in the Logout Token to identify the RP session with the OP when the backchannel_logout_uri is used. If omitted, the default value is false.
	BackChannelLogoutSessionRequired *bool `json:"backChannelLogoutSessionRequired"`
	// OpenID Connect Back-Channel Logout URI. RP URL that will cause the RP to log itself out when sent a Logout Token by the OP.
	BackChannelLogoutURI *string `json:"backChannelLogoutUri"`
	// Specify a time duration in milliseconds, seconds, minutes, hours. For example, 1h, 1m, 1s, 1ms.
	ClientCredentialsGrantAccessTokenLifespan *string `json:"clientCredentialsGrantAccessTokenLifespan"`
	// OAuth 2.0 Client ID. The ID is autogenerated and immutable.
	ClientID *string `json:"clientId"`
	// OAuth 2.0 Client Name. The human-readable name of the client to be presented to the end-user during authorization.
	ClientName *string `json:"clientName"`
	// OAuth 2.0 Client Secret. The secret will be included in the create request as cleartext, and then never again. The secret is kept in hashed format and is not recoverable once lost.
	ClientSecret *string `json:"clientSecret"`
	// OAuth 2.0 Client Secret Expires At. The field is currently not supported and its value is always 0.
	ClientSecretExpiresAt *int64 `json:"ClientSecretExpiresAt"`
	// OAuth 2.0 Client URI. ClientURI is a URL string of a web page providing information about the client. If present, the server SHOULD display this URL to the end-user in a clickable fashion.
	ClientURI *string `json:"clientUri"`
	// OAuth 2.0 Client Contacts. Contacts is an array of strings representing ways to contact people responsible for this client, typically email addresses.
	Contacts []string `json:"contacts"`
	// OAuth 2.0 Client Creation Date. CreatedAt returns the timestamp of the client's creation.
	CreatedAt *time.Time `json:"createdAt"`
	// OpenID Connect Front-Channel Logout Session Required. Boolean value specifying whether the RP requires that iss (issuer) and sid (session ID) query parameters be included to identify the RP session with the OP when the frontchannel_logout_uri is used. If omitted, the default value is false.
	FrontchannelLogoutSessionRequired *bool `json:"frontchannelLogoutSessionRequired"`
	// OpenID Connect Front-Channel Logout URI. RP URL that will cause the RP to log itself out when rendered in an iframe by the OP.
	FrontchannelLogoutURI *string  `json:"frontchannelLogoutUri"`
	GrantTypes            []string `json:"grantTypes"`
	// Specify a time duration in milliseconds, seconds, minutes, hours. For example, 1h, 1m, 1s, 1ms.
	ImplicitGrantAccessTokenLifespan *string `json:"implicitGrantAccessTokenLifespan"`
	// Specify a time duration in milliseconds, seconds, minutes, hours. For example, 1h, 1m, 1s, 1ms.
	ImplicitGrantIDTokenLifespan *string `json:"implicitGrantIdTokenLifespan"`
	// OAuth 2.0 Client JSON Web Key Set. Client's JSON Web Key Set [JWK] document, passed by value. The semantics of the jwks parameter are the same as the jwks_uri parameter, other than that the JWK Set is passed by value, rather than by reference. This parameter is intended only to be used by Clients that, for some reason, are unable to use the jwks_uri parameter, for instance, by native applications that might not have a location to host the contents of the JWK Set. If a Client can use jwks_uri, it MUST NOT use jwks. One significant downside of jwks is that it does not enable key rotation (which jwks_uri does, as described in Section 10 of OpenID Connect Core 1.0 [OpenID.Core]). The jwks_uri and jwks parameters MUST NOT be used together.
	Jwks map[string]interface{} `json:"jwks"`
	// OAuth 2.0 Client JSON Web Key Set URI. Client's JSON Web Key Set [JWK] document URI, passed by reference. The semantics of the jwks_uri parameter are the same as the jwks parameter, other than that the JWK Set is passed by reference, rather than by value. The jwks_uri and jwks parameters MUST NOT be used together.
	JwksURI *string `json:"jwksUri"`
	// Specify a time duration in milliseconds, seconds, minutes, hours. For example, 1h, 1m, 1s, 1ms.
	JwtBearerGrantAccessTokenLifespan *string `json:"jwtBearerGrantAccessTokenLifespan"`
	// OAuth 2.0 Client Logo URI. A URL string referencing the client's logo.
	LogoURI *string `json:"logoUri"`
	// OAuth 2.0 Client Metadata. Metadata is a map of key-value pairs that contain additional information about the client.
	Metadata map[string]interface{} `json:"metadata"`
	// OAuth 2.0 Client Owner. Owner is a string identifying the owner of the OAuth 2.0 Client.
	Owner *string `json:"owner"`
	// OAuth 2.0 Client Policy URI. PolicyURI is a URL string that points to a human-readable privacy policy document that describes how the deployment organization collects, uses, retains, and discloses personal data.
	PolicyURI *string `json:"policyUri"`
	// OAuth 2.0 Client Post Logout Redirect URIs. PostLogoutRedirectUris is an array of allowed URLs to which the RP is allowed to redirect the End-User's User Agent after a logout has been performed.
	PostLogoutRedirectUris []string `json:"postLogoutRedirectUris"`
	// OAuth 2.0 Client Redirect URIs. RedirectUris is an array of allowed redirect URLs for the OAuth 2.0 Client.
	RedirectUris []string `json:"redirectUris"`
	// OAuth 2.0 Client Response Types. ResponseTypes is an array of the OAuth 2.0 response type strings that the client can use at the Authorization Endpoint.
	ResponseTypes []string `json:"responseTypes"`
	// OAuth 2.0 Client Scope. Scope is a string containing a space-separated list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client can use when requesting access tokens.
	Scope *string `json:"scope"`
	// OAuth 2.0 Client Sector Identifier URI. SectorIdentifierURI is a URL string using the https scheme referencing a file with a single JSON array of redirect_uri values.
	SectorIdentifierURI *string `json:"sectorIdentifierUri"`
	// OAuth 2.0 Client Subject Type. SubjectType requested for responses to this Client. The subject_types_supported Discovery parameter contains a list of the supported subject_type values for this server. Valid types include pairwise and public.
	SubjectType *string `json:"subjectType"`
	// OAuth 2.0 Client Token Endpoint Auth Method. TokenEndpointAuthMethod is the requested Client Authentication method for the Token Endpoint. The token_endpoint_auth_methods_supported Discovery parameter contains a list of the authentication methods supported by this server. Valid types include client_secret_post, client_secret_basic, private_key_jwt, and none.
	TokenEndpointAuthMethod *string `json:"tokenEndpointAuthMethod"`
	// OAuth 2.0 Client Token Endpoint Auth Signing Algorithm. TokenEndpointAuthSigningAlgorithm is the requested Client Authentication signing algorithm for the Token Endpoint. The token_endpoint_auth_signing_alg_values_supported Discovery parameter contains a list of the supported signing algorithms for the token endpoint.
	TokenEndpointAuthSigningAlgorithm *string `json:"tokenEndpointAuthSigningAlgorithm"`
	// OAuth 2.0 Client Terms of Service URI. A URL string pointing to a human-readable terms of service document for the client that describes a contractual relationship between the end-user and the client that the end-user accepts when authorizing the client.
	TosURI *string `json:"tosUri"`
	// OAuth 2.0 Client Updated Date. UpdatedAt returns the timestamp of the client's last update.
	UpdatedAt *time.Time `json:"updatedAt"`
	// OpenID Connect Userinfo Signed Response Algorithm. UserInfoSignedResponseAlg is a string containing the JWS signing algorithm (alg) parameter required for signing UserInfo Responses. The value none MAY be used, which indicates that the UserInfo Response will not be signed. The alg value RS256 MUST be used unless support for RS256 has been explicitly disabled. If support for RS256 has been disabled, the value none MUST be used.
	UserinfoSignedResponseAlgorithm *string `json:"userinfoSignedResponseAlgorithm"`
	// The organization that owns this OAuth2 Client.
	Organization *Organization `json:"organization"`
	// The users and groups that are allowed to login with this OAuth2 Client.
	LoginBindings *LoginBindings `json:"loginBindings"`
}

// Representation a tenant in the Grafana observability stack where metrics, logs and traces can be sent to or retrieved from.
type ObservabilityTenant struct {
	// The unique ID of the tenant.
	ID string `json:"id"`
	// The name of the tenant.
	Name *string `json:"name"`
	// The organization that the tenant belongs to.
	Organization *Organization `json:"organization"`
	// The users that are admins of the organization.
	Viewers *ObservabilityTenantViewers `json:"viewers"`
	// The users and groups that can edit a tenant to add users, groups or oauth2 clients to it.
	Editors *ObservabilityTenantEditors `json:"editors"`
}

// Representation of the users and groups that can edit a tenant.
type ObservabilityTenantEditors struct {
	// The users that can edit a tenant.
	Users []*User `json:"users"`
	// The groups that can edit a tenant.
	Groups []*Group `json:"groups"`
}

// Representation of the users, groups and oauth2 clients that can view or send data a tenant.
type ObservabilityTenantViewers struct {
	// The users that can view a tenant.
	Users []*User `json:"users"`
	// The groups that can view a tenant.
	Groups []*Group `json:"groups"`
	// The oauth2 clients that can send data a tenant.
	Oauth2Clients []*OAuth2Client `json:"oauth2Clients"`
}

// Representation an Organization in the auth stack.
type Organization struct {
	// The name of the organization.
	Name string `json:"name"`
	// The users that are admins of the organization.
	Admins []*User `json:"admins"`
}

// Representation of the information about a user sourced from Kratos.
type User struct {
	// The unique ID of the user.
	ID string `json:"id"`
	// The user's full name.
	Name *Name `json:"name"`
	// The user's email address.
	Email string `json:"email"`
	// The groups the user belongs to.
	Groups []*Group `json:"groups"`
	// The organization the user belongs to.
	Organization *Organization `json:"organization"`
	// The link a user can use to recover their account.
	RecoveryLink *string `json:"recoveryLink"`
}
