package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/pluralsh/oauth-playground/api-server/graph/model"
)

// ListGroups is the resolver for the listGroups field.
func (r *queryResolver) ListGroups(ctx context.Context) ([]*model.Group, error) {
	panic(fmt.Errorf("not implemented: ListGroups - listGroups"))
}
