package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/pluralsh/oauth-playground/api-server/graph/model"
)

// AcceptOAuth2ConsentRequest is the resolver for the acceptOAuth2ConsentRequest field.
func (r *mutationResolver) AcceptOAuth2ConsentRequest(ctx context.Context, challenge string, grantAccessTokenAudience *string, grantScope []string, remember *bool, rememberFor *int64, session *model.AcceptOAuth2ConsentRequestSession) (*model.OAuth2RedirectTo, error) {
	panic(fmt.Errorf("not implemented: AcceptOAuth2ConsentRequest - acceptOAuth2ConsentRequest"))
}

// RejectOAuth2ConsentRequest is the resolver for the rejectOAuth2ConsentRequest field.
func (r *mutationResolver) RejectOAuth2ConsentRequest(ctx context.Context, challenge string) (*model.OAuth2RedirectTo, error) {
	panic(fmt.Errorf("not implemented: RejectOAuth2ConsentRequest - rejectOAuth2ConsentRequest"))
}

// Oauth2ConsentRequest is the resolver for the oauth2ConsentRequest field.
func (r *queryResolver) Oauth2ConsentRequest(ctx context.Context, challenge string) (*model.OAuth2ConsentRequest, error) {
	panic(fmt.Errorf("not implemented: Oauth2ConsentRequest - oauth2ConsentRequest"))
}
