package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/pluralsh/oauth-playground/api-server/graph/generated"
	"github.com/pluralsh/oauth-playground/api-server/graph/model"
)

// Organization is the resolver for the organization field.
func (r *mutationResolver) Organization(ctx context.Context, name string, admins []string) (*model.Organization, error) {
	return r.C.UpdateOrganization(ctx, name, admins)
}

// Admins is the resolver for the admins field.
func (r *organizationResolver) Admins(ctx context.Context, obj *model.Organization) ([]*model.User, error) {
	return r.C.GetOrganizationAdmins(ctx, obj.Name)
}

// ListOrganizations is the resolver for the listOrganizations field.
func (r *queryResolver) ListOrganizations(ctx context.Context) ([]*model.Organization, error) {
	return r.C.ListOrganizations(ctx)
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, name string) (*model.Organization, error) {
	return r.C.GetOrganization(ctx, name)
}

// Organization returns generated.OrganizationResolver implementation.
func (r *Resolver) Organization() generated.OrganizationResolver { return &organizationResolver{r} }

type organizationResolver struct{ *Resolver }
